baseurl = 'https://blog.keiji.dev/'
name = 'めがねをかけるんだ'
title = 'めがねをかけるんだ'
description = 'Don&#039;t take your glasses off.'
canonifyurls = true
hasCJKLanguage = true
languageCode = "ja"
author = "Keiji ARIYAMA"
copyright = "Keiji ARIYAMA All rights reserved."
googleAnalytics = "G-RTC3ZY943S"
theme = "harbor"
enableInlineShortcodes = true

[params.logo]
  url = "logo.png" # /images/icon.png
  alt = "Logo"
  title = "めがねをかけるんだ"

[params]
  dateformat = "2006-01-02"
  customCSS = ["css/default.css"]
  description = "Don't take your glasses off."
  images = ["/images/logo.png"]
#  enableGoogleAnalytics = true

[[params.nav]]
  identifier = "profile"
  name = "Profile"
  icon = "fas fa-user fa-lg"
  url = "/profile/"
  weight = 1

[[params.nav]]
  identifier = "licenses"
  name = "Licenses"
  icon = "fab fa-osi fa-lg"
  url = "/licenses/"
  weight = 1

[markup.goldmark.renderer]
unsafe= true