url: 'https://blog.keiji.io'
name: 'めがねをかけるんだ'
title: 'めがねをかけるんだ'
description: 'Don&#039;t take your glasses off.'
publishdir: 'public'
contentdir: 'content'
canonifyurls: true
hasCJKLanguage: true
languageCode: "ja"
author: "rakuishi"
copyright: "rakuishi All rights reserved."
googleanalytics: "UA-12345678-9"

params:
  logo: "/images/logo.jpg"
  twitter: "https://twitter.com/keiji_ariyama"
  facebook: "https://www.facebook.com/keiji.ariyama"
  github: "https://github.com/keiji"
