name: Hugo-Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup
        run: |
          git submodule init
          git submodule update
      - name: Build Site'
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.133.0'
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./public
          CLEAN: true  
